const arrDataCourse = [
    {
        id: 1,
        name: "FRONTEND NEWBIE",
        desc: "Khóa học phù hợp cho các bạn mới tiếp xúc với web và Frontend cũng như các bạn cần nâng cao kiến thức Frontend",
        time: "40 buổi",
        price: "9,500,000 VNĐ",
        timeline: [
            {
                id: 1,
                title: "HTML/CSS",
                time: "10 buổi",
                lyThuyet: [
                    "Các kiến thức cơ bản của web",
                    "Các thẻ HTML và cách áp dụng thực tế",
                    "Các thuộc tính CSS và bài áp dụng tương ứng",
                    "CÁCH ĐẶT TÊN CLASS + VIẾT CLEAN CODE HTML / CSS",
                    "RESPONSOVE trên mobile và ipad",
                    "ANIMATION hover & keyframe",
                ],
                baiTap: ["Profile facebook", "Form login", "Header", "Footer", "List Product", "Animation loading"],
                toTal: ["30+ Mini Project", "1 big Project Landingpage"],
            },
            {
                id: 2,
                title: "BOOTSTRAP",
                time: "2 buổi",
                lyThuyet: ["Cách sử dụng Boostrap 5", "Cách chia layout bằng BS5", "Cách sử dụng các component trong BS5"],
                baiTap: ["Chia layout với GRID", "List product"],
                toTal: ["5+ Mini Project", "1 big Project Landingpage"],
            },
            {
                id: 3,
                title: "SCSS",
                time: "3 buổi",
                lyThuyet: ["Cách cấu hình scss", "Cách viết scss", "Cách sử dụng variable", "Cách tạo mixin"],
                baiTap: ["List product", "Header", "Footer"],
                toTal: ["10+ Mini Project", "1 big Project Landingpage"],
            },
            {
                id: 4,
                title: "JAVASCRIPT CƠ BẢN",
                time: "15 buổi",
                lyThuyet: [
                    "Các cách khai báo biến, hoisting trong JS",
                    "Câu lệnh điều kiện IF/ELSE",
                    "FUNCTION và các loại FUNCTION",
                    "ARRAY và các phương thức trong ARRAY",
                    "OBJECT và các phương thức trong OBJECT",
                    "Các hàm xử lý thời gian",
                    "DOM VÀ EVENT",
                    "REGULAR EXPRESSION",
                ],
                baiTap: [
                    "20+ Bài tập xử lý IF/ELSE",
                    "10+ Bài tập xử lý FUNCTION",
                    "50+ Bài tập xử lý ARRAY",
                    "30+ Bài tập xử lý OBJECT",
                    "Dropdown",
                    "Darkmode",
                    "Password check",
                    "Game Oản tù tì",
                    "CountDown",
                    "Slide ảnh",
                    "Tab",
                ],
                toTal: ["Validate form", "Game tài xỉu", "Todolist", "CRUD Quản lý siêu thị"],
            },
            {
                id: 5,
                title: "JAVASCRIPT NÂNG CAO",
                time: "5 buổi",
                lyThuyet: ["Đồng bộ và bất đồng bộ", "Callback", "Promise", "Fetch API", "ASYNC/AWAIT", "RESTFUL API"],
                baiTap: ["Weather APP", "Dictionary APP", "Country APP", "Pokemon APP", "Meal APP", "LOGIN/REGISTER RESFUL API", "CRUD RESFULL API"],
                toTal: ["PROECT MOVIE"],
            },
            {
                id: 6,
                title: "FINNAL PROJECT",
                time: "5 buổi",
                lyThuyet: [
                    "Áp dụng kiến thức về SCSS để tổ chức CSS",
                    "Áp dụng kiến thức BOOTSTRAP để chia layout và responsive",
                    "Áp dụng kiến thức API để fetch api",
                    "Dùng JSON-SERVER để tạo RESFUL API",
                ],
                baiTap: [
                    "Xây dựng tính năng lọc, search sản phẩm",
                    "Xây dựng tính năng thêm sản phẩm vào giỏ hàng",
                    "Xây dựng tính năng đăng kí đăng nhập và phân quyền",
                    "Quản lý sản phẩm trong admin bao gồm thêm/xóa/sửa",
                    "Các tính năng liên quan",
                ],
                toTal: ["PROJECT THƯƠNG MẠI ĐIỆN TỬ + ADMIN QUẢN LÝ"],
            },
        ],
    },
    {
        id: 2,
        name: "HTML/CSS/SCSS THỰC CHIẾN",
        desc: "Khóa học tập trung vào HTML/CSS và tư duy phân tích layout giúp UI/UX có cách nhìn tốt hơn về Code",
        time: "Chỉ gói gọn trong 40 buổi học",
        timeline: [
            {
                id: 1,
                title: "HTML/CSS",
                time: "20 buổi",
                lyThuyet: [
                    "Các kiến thức cơ bản của web",
                    "Các thẻ HTML và cách áp dụng đụng",
                    "Các thuộc tính CSS và bài áp dụng tương ứng",
                    "CÁCH VIẾT CLEAN CODE HTML VÀ CSS",
                    "RESPONSOVE trên mobile và ipad",
                    "ANIMATION hover & keyframe",
                ],
                baiTap: ["Profile facebook", "Form login", "Header", "Footer", "List Product", "Animation loading"],
                toTal: ["30+ Mini Project", "1 big Project Landingpage"],
            },
        ],
    },
];
export default arrDataCourse;
